export const CRYPTO_UNIVERSE_TARGET_COUNT = 250
export const CRYPTO_UNIVERSE_CANDIDATE_RANK_MAX = 500
export const CRYPTO_UNIVERSE_EXCHANGE = "BINANCE"
export const CRYPTO_UNIVERSE_QUOTE_SYMBOL = "USDT"
export const CRYPTO_UNIVERSE_INSTRUMENT_TYPE = "swap"
export const CRYPTO_UNIVERSE_TYPE_SPECIFICATION = "perpetual"
