import { DERIVATIVE_INDICATOR_DEFINITIONS } from "./derivatives.js"
import { FINANCIAL_INDICATOR_DEFINITIONS } from "./financials.js"
import { NETWORK_INDICATOR_DEFINITIONS } from "./network.js"
import { OWNERSHIP_INDICATOR_DEFINITIONS } from "./ownership.js"
import { SOCIAL_INDICATOR_DEFINITIONS } from "./social.js"
import { VOLUME_INDICATOR_DEFINITIONS } from "./volume.js"

export { defineIndicator } from "./definition.js"
export {
  DERIVATIVE_INDICATOR_DEFINITIONS,
  FINANCIAL_INDICATOR_DEFINITIONS,
  NETWORK_INDICATOR_DEFINITIONS,
  OWNERSHIP_INDICATOR_DEFINITIONS,
  SOCIAL_INDICATOR_DEFINITIONS,
  VOLUME_INDICATOR_DEFINITIONS,
}

export const INDICATOR_DEFINITIONS = Object.freeze([
  ...DERIVATIVE_INDICATOR_DEFINITIONS,
  ...FINANCIAL_INDICATOR_DEFINITIONS,
  ...NETWORK_INDICATOR_DEFINITIONS,
  ...OWNERSHIP_INDICATOR_DEFINITIONS,
  ...SOCIAL_INDICATOR_DEFINITIONS,
  ...VOLUME_INDICATOR_DEFINITIONS,
])
