import { defineIndicator } from "./definition.js"

const VERSION_7 = "7.0"
const VERSION_6 = "6.0"

function defineNetworkIndicator ({ plot, ...definition }) {
  return defineIndicator("network", {
    ...definition,
    fields: {
      value: plot,
    },
  })
}

export const NETWORK_INDICATOR_DEFINITIONS = Object.freeze([
  defineNetworkIndicator({
    key: "addressesWithBalance",
    id: "STD;CryptoFund_total_addresses_with_balance",
    version: VERSION_7,
    name: "Addresses with balance",
    plot: "Addresses_with_balance",
  }),
  defineNetworkIndicator({
    key: "newFundedAddresses",
    id: "STD;CryptoFund_addresses_new",
    version: VERSION_7,
    name: "New funded addresses",
    plot: "New_funded_addresses",
  }),
  defineNetworkIndicator({
    key: "activeAddresses",
    id: "STD;CryptoFund_addresses_active",
    version: VERSION_7,
    name: "Active addresses",
    plot: "Active_addresses",
  }),
  defineNetworkIndicator({
    key: "transactionVolumeUsd",
    id: "STD;CryptoFund_txs_volume_usd",
    version: VERSION_7,
    name: "Transaction volume in USD",
    plot: "Transaction_volume_in_USD",
  }),
  defineNetworkIndicator({
    key: "transactionVolume",
    id: "STD;CryptoFund_txs_volume",
    version: VERSION_7,
    name: "Transaction volume",
    plot: "Transaction_volume",
  }),
  defineNetworkIndicator({
    key: "averageTransactionVolumeUsd",
    id: "STD;CryptoFund_average_transaction_usd",
    version: VERSION_7,
    name: "Average transaction volume in USD",
    plot: "Average_transaction_volume_in_USD",
  }),
  defineNetworkIndicator({
    key: "averageTransactionVolume",
    id: "STD;CryptoFund_average_transaction",
    version: VERSION_7,
    name: "Average transaction volume",
    plot: "Average_transaction_volume",
  }),
  defineNetworkIndicator({
    key: "transactionCount",
    id: "STD;CryptoFund_txs_count",
    version: VERSION_7,
    name: "Transaction count",
    plot: "Transaction_count",
  }),
  defineNetworkIndicator({
    key: "largeTransactionCount",
    id: "STD;CryptoFund_large_tx_count",
    version: VERSION_7,
    name: "Large transaction count",
    plot: "Large_transaction_count",
  }),
  defineNetworkIndicator({
    key: "largeTransactionVolumeUsd",
    id: "STD;CryptoFund_large_tx_volume_usd",
    version: VERSION_7,
    name: "Large transaction volume in USD",
    plot: "Large_transaction_volume_in_USD",
  }),
  defineNetworkIndicator({
    key: "largeTransactionVolume",
    id: "STD;CryptoFund_large_tx_volume",
    version: VERSION_7,
    name: "Large transaction volume",
    plot: "Large_transaction_volume",
  }),
  defineNetworkIndicator({
    key: "totalValueLocked",
    id: "STD;CryptoFund_tvl",
    version: VERSION_7,
    name: "Total value locked",
    plot: "Total_value_locked",
  }),
  defineNetworkIndicator({
    key: "transactionFeesUsd",
    id: "STD;CryptoFund_fees_usd",
    version: VERSION_7,
    name: "Transaction fees in USD",
    plot: "Transaction_fees_in_USD",
  }),
  defineNetworkIndicator({
    key: "transactionFees",
    id: "STD;CryptoFund_fees_total",
    version: VERSION_6,
    name: "Transaction fees",
    plot: "Transaction_fees",
  }),
  defineNetworkIndicator({
    key: "meanTransactionFeesUsd",
    id: "STD;CryptoFund_fees_mean_usd",
    version: VERSION_6,
    name: "Mean transaction fees in USD",
    plot: "Mean_transaction_fees_in_USD",
  }),
  defineNetworkIndicator({
    key: "meanTransactionFees",
    id: "STD;CryptoFund_fees_mean",
    version: VERSION_6,
    name: "Mean transaction fees",
    plot: "Mean_transaction_fees",
  }),
  defineNetworkIndicator({
    key: "medianTransactionFeesUsd",
    id: "STD;CryptoFund_fees_median_usd",
    version: VERSION_6,
    name: "Median transaction fees in USD",
    plot: "Median_transaction_fees_in_USD",
  }),
  defineNetworkIndicator({
    key: "medianTransactionFees",
    id: "STD;CryptoFund_fees_median",
    version: VERSION_6,
    name: "Median transaction fees",
    plot: "Median_transaction_fees",
  }),
  defineNetworkIndicator({
    key: "transactionRate",
    id: "STD;CryptoFund_transaction_rate",
    version: VERSION_6,
    name: "Transaction rate",
    plot: "Transaction_rate",
  }),
  defineNetworkIndicator({
    key: "transferRate",
    id: "STD;CryptoFund_transfer_rate",
    version: VERSION_6,
    name: "Transfer rate",
    plot: "Transfer_rate",
  }),
  defineNetworkIndicator({
    key: "transferCount",
    id: "STD;CryptoFund_transfer_count",
    version: VERSION_6,
    name: "Transfer count",
    plot: "Transfer_count",
  }),
  defineNetworkIndicator({
    key: "meanTransferVolumeUsd",
    id: "STD;CryptoFund_transfer_volume_mean_usd",
    version: VERSION_6,
    name: "Mean transfer volume in USD",
    plot: "Mean_transfer_volume_in_USD",
  }),
  defineNetworkIndicator({
    key: "meanTransferVolume",
    id: "STD;CryptoFund_transfer_volume_mean",
    version: VERSION_6,
    name: "Mean transfer volume",
    plot: "Mean_transfer_volume",
  }),
  defineNetworkIndicator({
    key: "medianTransferVolumeUsd",
    id: "STD;CryptoFund_transfer_volume_median_usd",
    version: VERSION_6,
    name: "Median transfer volume in USD",
    plot: "Median_transfer_volume_in_USD",
  }),
  defineNetworkIndicator({
    key: "medianTransferVolume",
    id: "STD;CryptoFund_transfer_volume_median",
    version: VERSION_6,
    name: "Median transfer volume",
    plot: "Median_transfer_volume",
  }),
  defineNetworkIndicator({
    key: "sendingAddresses",
    id: "STD;CryptoFund_sending_addresses",
    version: VERSION_6,
    name: "Sending addresses",
    plot: "Sending_addresses",
  }),
  defineNetworkIndicator({
    key: "receivingAddresses",
    id: "STD;CryptoFund_receiving_addresses",
    version: VERSION_6,
    name: "Receiving addresses",
    plot: "Receiving_addresses",
  }),
  defineNetworkIndicator({
    key: "totalAddresses",
    id: "STD;CryptoFund_total_addresses",
    version: VERSION_6,
    name: "Total addresses",
    plot: "Total_addresses",
  }),
  defineNetworkIndicator({
    key: "spentOutputProfitRatio",
    id: "STD;CryptoFund_sopr",
    version: VERSION_6,
    name: "Spent Output Profit Ratio",
    plot: "Spent_Output_Profit_Ratio",
  }),
  defineNetworkIndicator({
    key: "blockHeight",
    id: "STD;CryptoFund_block_height",
    version: VERSION_6,
    name: "Block height",
    plot: "Block_height",
  }),
  defineNetworkIndicator({
    key: "blocksMined",
    id: "STD;CryptoFund_blocks_mined",
    version: VERSION_6,
    name: "Blocks mined",
    plot: "Blocks_mined",
  }),
  defineNetworkIndicator({
    key: "meanBlockInterval",
    id: "STD;CryptoFund_block_interval_mean",
    version: VERSION_6,
    name: "Mean block interval",
    plot: "Mean_block_interval",
  }),
  defineNetworkIndicator({
    key: "medianBlockInterval",
    id: "STD;CryptoFund_block_interval_median",
    version: VERSION_6,
    name: "Median block interval",
    plot: "Median_block_interval",
  }),
  defineNetworkIndicator({
    key: "totalBlockSizeBytes",
    id: "STD;CryptoFund_block_size_total",
    version: VERSION_6,
    name: "Total block size in bytes",
    plot: "Total_block_size_in_bytes",
  }),
  defineNetworkIndicator({
    key: "meanBlockSizeBytes",
    id: "STD;CryptoFund_block_size_mean",
    version: VERSION_6,
    name: "Mean block size in bytes",
    plot: "Mean_block_size_in_bytes",
  }),
  defineNetworkIndicator({
    key: "hashRate",
    id: "STD;CryptoFund_hash_rate",
    version: VERSION_6,
    name: "Hash Rate",
    plot: "Hash_Rate",
  }),
  defineNetworkIndicator({
    key: "difficulty",
    id: "STD;CryptoFund_difficulty",
    version: VERSION_6,
    name: "Difficulty",
    plot: "Difficulty",
  }),
  defineNetworkIndicator({
    key: "totalUtxos",
    id: "STD;CryptoFund_utxo_total",
    version: VERSION_6,
    name: "Total UTXOs",
    plot: "Total_UTXOs",
  }),
  defineNetworkIndicator({
    key: "createdUtxos",
    id: "STD;CryptoFund_utxo_created",
    version: VERSION_6,
    name: "Created UTXOs",
    plot: "Created_UTXOs",
  }),
  defineNetworkIndicator({
    key: "spentUtxos",
    id: "STD;CryptoFund_utxo_spent",
    version: VERSION_6,
    name: "Spent UTXOs",
    plot: "Spent_UTXOs",
  }),
  defineNetworkIndicator({
    key: "totalUtxoValueCreatedUsd",
    id: "STD;CryptoFund_utxo_value_created_total_usd",
    version: VERSION_6,
    name: "Total UTXO value created in USD",
    plot: "Total_UTXO_value_created_in_USD",
  }),
  defineNetworkIndicator({
    key: "totalUtxoValueCreated",
    id: "STD;CryptoFund_utxo_value_created_total",
    version: VERSION_6,
    name: "Total UTXO value created",
    plot: "Total_UTXO_value_created",
  }),
  defineNetworkIndicator({
    key: "meanUtxoValueCreatedUsd",
    id: "STD;CryptoFund_utxo_value_created_mean_usd",
    version: VERSION_6,
    name: "Mean UTXO value created in USD",
    plot: "Mean_UTXO_value_created_in_USD",
  }),
  defineNetworkIndicator({
    key: "meanUtxoValueCreated",
    id: "STD;CryptoFund_utxo_value_created_mean",
    version: VERSION_6,
    name: "Mean UTXO value created",
    plot: "Mean_UTXO_value_created",
  }),
  defineNetworkIndicator({
    key: "medianUtxoValueCreatedUsd",
    id: "STD;CryptoFund_utxo_value_created_median_usd",
    version: VERSION_6,
    name: "Median UTXO value created in USD",
    plot: "Median_UTXO_value_created_in_USD",
  }),
  defineNetworkIndicator({
    key: "medianUtxoValueCreated",
    id: "STD;CryptoFund_utxo_value_created_median",
    version: VERSION_6,
    name: "Median UTXO value created",
    plot: "Median_UTXO_value_created",
  }),
  defineNetworkIndicator({
    key: "totalUtxoValueSpentUsd",
    id: "STD;CryptoFund_utxo_value_spent_total_usd",
    version: VERSION_6,
    name: "Total UTXO value spent in USD",
    plot: "Total_UTXO_value_spent_in_USD",
  }),
  defineNetworkIndicator({
    key: "totalUtxoValueSpent",
    id: "STD;CryptoFund_utxo_value_spent_total",
    version: VERSION_6,
    name: "Total UTXO value spent",
    plot: "Total_UTXO_value_spent",
  }),
  defineNetworkIndicator({
    key: "meanUtxoValueSpentUsd",
    id: "STD;CryptoFund_utxo_value_spent_mean_usd",
    version: VERSION_6,
    name: "Mean UTXO value spent in USD",
    plot: "Mean_UTXO_value_spent_in_USD",
  }),
  defineNetworkIndicator({
    key: "meanUtxoValueSpent",
    id: "STD;CryptoFund_utxo_value_spent_mean",
    version: VERSION_6,
    name: "Mean UTXO value spent",
    plot: "Mean_UTXO_value_spent",
  }),
  defineNetworkIndicator({
    key: "medianUtxoValueSpentUsd",
    id: "STD;CryptoFund_utxo_value_spent_median_usd",
    version: VERSION_6,
    name: "Median UTXO value spent in USD",
    plot: "Median_UTXO_value_spent_in_USD",
  }),
  defineNetworkIndicator({
    key: "medianUtxoValueSpent",
    id: "STD;CryptoFund_utxo_value_spent_median",
    version: VERSION_6,
    name: "Median UTXO value spent",
    plot: "Median_UTXO_value_spent",
  }),
  defineNetworkIndicator({
    key: "totalTransactionSizeBytes",
    id: "STD;CryptoFund_transaction_size_total",
    version: VERSION_6,
    name: "Total transactions size in bytes",
    plot: "Total_transactions_size_in_bytes",
  }),
  defineNetworkIndicator({
    key: "meanTransactionSizeBytes",
    id: "STD;CryptoFund_transaction_size_mean",
    version: VERSION_6,
    name: "Mean transaction size in bytes",
    plot: "Mean_transaction_size_in_bytes",
  }),
  defineNetworkIndicator({
    key: "elSalvadorGovernmentBalanceBtc",
    id: "STD;CryptoFund_el_salvador_government_balance",
    version: VERSION_6,
    name: "El Salvador Government balance in BTC",
    plot: "El_Salvador_Government_balance_in_BTC",
  }),
  defineNetworkIndicator({
    key: "elSalvadorGovernmentBalanceUsd",
    id: "STD;CryptoFund_el_salvador_government_balance_usd",
    version: VERSION_6,
    name: "El Salvador Government balance in USD",
    plot: "El_Salvador_Government_balance_in_USD",
  }),
  defineNetworkIndicator({
    key: "powerLawModel",
    id: "STD;CryptoFund_power_law_model",
    version: VERSION_6,
    name: "Power-Law Model",
    plot: "PowerLaw_Model",
  }),
  defineNetworkIndicator({
    key: "stockToFlowRatioUsd",
    id: "STD;CryptoFund_stock_to_flow_ratio",
    version: VERSION_6,
    name: "Stock-to-Flow Ratio in USD",
    plot: "StocktoFlow_Ratio_in_USD",
  }),
])
